// _TO_CONVERT_NOW/0example-react-recent/Pages/Teams/Partials/CreateTeamForm.tsx
import React, { FormEventHandler } from 'react';
import { useForm, usePage } from '@inertiajs/react';
import FormSection from '@/Components/FormSection';
import InputError from '@/Components/InputError';
import InputLabel from '@/Components/InputLabel';
import PrimaryButton from '@/Components/PrimaryButton';
import TextInput from '@/Components/TextInput';

const CreateTeamForm: React.FC = () => {
  const page: any = usePage();
  const form = useForm({
    name: '',
  });

  const createTeam: FormEventHandler = (e) => {
    e.preventDefault();
    form.post(route('teams.store'), {
      errorBag: 'createTeam',
      preserveScroll: true,
    });
  };

  return (
    <FormSection
      onSubmit={createTeam}
      title="Team Details"
      description="Create a new team to collaborate with others on projects."
      actions={
        <PrimaryButton className={form.processing ? 'opacity-25' : ''} disabled={form.processing}>
          Create
        </PrimaryButton>
      }
    >
      <div className="col-span-6">
        <InputLabel value="Team Owner" />
        <div className="flex items-center mt-2">
          <img
            className="object-cover w-12 h-12 rounded-full"
            src={page.props.auth.user.profile_photo_url}
            alt={page.props.auth.user.name}
          />
          <div className="leading-tight ms-4">
            <div className="text-gray-900 dark:text-white">{page.props.auth.user.name}</div>
            <div className="text-sm text-gray-700 dark:text-gray-300">{page.props.auth.user.email}</div>
          </div>
        </div>
      </div>

      <div className="col-span-6 sm:col-span-4">
        <InputLabel htmlFor="name" value="Team Name" />
        <TextInput
          id="name"
          value={form.data.name}
          onChange={(e) => form.setData('name', e.target.value)}
          type="text"
          className="block w-full mt-1"
          autoFocus
        />
        <InputError message={form.errors.name} className="mt-2" />
      </div>
    </FormSection>
  );
};

export default CreateTeamForm;

// _TO_CONVERT_NOW/0example-react-recent/Pages/Teams/Partials/CreateTeamForm.vue
<script lang="ts" setup>
import { useForm } from '@inertiajs/vue3';
import FormSection from '@/Components/FormSection.vue';
import InputError from '@/Components/InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import TextInput from '@/Components/TextInput.vue';

const form = useForm({
  name: '',
});

const createTeam = () => {
  form.post(route('teams.store'), {
    errorBag: 'createTeam',
    preserveScroll: true,
  });
};
</script>

<template>
  <FormSection @submitted="createTeam">
    <template #title> Team Details </template>

    <template #description> Create a new team to collaborate with others on projects. </template>

    <template #form>
      <div class="col-span-6">
        <InputLabel value="Team Owner" />

        <div class="flex items-center mt-2">
          <img
            class="object-cover w-12 h-12 rounded-full"
            :src="$page.props.auth.user.profile_photo_url"
            :alt="$page.props.auth.user.name"
          />

          <div class="ms-4 leading-tight">
            <div class="text-gray-900">{{ $page.props.auth.user.name }}</div>
            <div class="text-sm text-gray-700">
              {{ $page.props.auth.user.email }}
            </div>
          </div>
        </div>
      </div>

      <div class="col-span-6 sm:col-span-4">
        <InputLabel for="name" value="Team Name" />
        <TextInput id="name" v-model="form.name" type="text" class="block w-full mt-1" autofocus />
        <InputError :message="form.errors.name" class="mt-2" />
      </div>
    </template>

    <template #actions>
      <PrimaryButton :class="{ 'opacity-25': form.processing }" :disabled="form.processing"> Create </PrimaryButton>
    </template>
  </FormSection>
</template>
