// _TO_CONVERT_NOW/0example-react-recent/Pages/Teams/Partials/DeleteTeamForm.vue
<script lang="ts" setup>
import { ref } from 'vue';
import { useForm } from '@inertiajs/vue3';
import ActionSection from '@/Components/ActionSection.vue';
import ConfirmationModal from '@/Components/ConfirmationModal.vue';
import DangerButton from '@/Components/DangerButton.vue';
import SecondaryButton from '@/Components/SecondaryButton.vue';

const props = defineProps({
  team: Object,
});

const confirmingTeamDeletion = ref(false);
const form = useForm({});

const confirmTeamDeletion = () => {
  confirmingTeamDeletion.value = true;
};

const deleteTeam = () => {
  form.delete(route('teams.destroy', props.team), {
    errorBag: 'deleteTeam',
  });
};
</script>

<template>
  <ActionSection>
    <template #title> Delete Team </template>

    <template #description> Permanently delete this team. </template>

    <template #content>
      <div class="max-w-xl text-sm text-gray-600">
        Once a team is deleted, all of its resources and data will be permanently deleted. Before deleting this team, please download any
        data or information regarding this team that you wish to retain.
      </div>

      <div class="mt-5">
        <DangerButton @click="confirmTeamDeletion"> Delete Team </DangerButton>
      </div>

      <!-- Delete Team Confirmation Modal -->
      <ConfirmationModal :show="confirmingTeamDeletion" @close="confirmingTeamDeletion = false">
        <template #title> Delete Team </template>

        <template #content>
          Are you sure you want to delete this team? Once a team is deleted, all of its resources and data will be permanently deleted.
        </template>

        <template #footer>
          <SecondaryButton @click="confirmingTeamDeletion = false"> Cancel </SecondaryButton>

          <DangerButton class="ms-3" :class="{ 'opacity-25': form.processing }" :disabled="form.processing" @click="deleteTeam">
            Delete Team
          </DangerButton>
        </template>
      </ConfirmationModal>
    </template>
  </ActionSection>
</template>

// _TO_CONVERT_NOW/0example-react-recent/Pages/Teams/Partials/DeleteTeamForm.tsx
import React, { useState, FormEventHandler } from 'react';
import { useForm, usePage } from '@inertiajs/react';
import ActionSection from '@/Components/ActionSection';
import ConfirmationModal from '@/Components/ConfirmationModal';
import DangerButton from '@/Components/DangerButton';
import SecondaryButton from '@/Components/SecondaryButton';

interface DeleteTeamFormProps {
  team: any;
}

const DeleteTeamForm: React.FC<DeleteTeamFormProps> = ({ team }) => {
  const [confirmingTeamDeletion, setConfirmingTeamDeletion] = useState(false);
  const form = useForm({});

  const confirmTeamDeletion = () => {
    setConfirmingTeamDeletion(true);
  };

  const deleteTeam: FormEventHandler = (e) => {
    e.preventDefault();
    form.delete(route('teams.destroy', team), {
      errorBag: 'deleteTeam',
    });
  };

  return (
    <ActionSection
      title="Delete Team"
      description="Permanently delete this team."
      content={
        <>
          <div className="max-w-xl text-sm text-gray-600 dark:text-gray-400">
            Once a team is deleted, all of its resources and data will be permanently deleted. Before deleting this team, please download
            any data or information regarding this team that you wish to retain.
          </div>

          <div className="mt-5">
            <DangerButton onClick={confirmTeamDeletion}>Delete Team</DangerButton>
          </div>

          <ConfirmationModal
            show={confirmingTeamDeletion}
            onClose={() => setConfirmingTeamDeletion(false)}
            title="Delete Team"
            content="Are you sure you want to delete this team? Once a team is deleted, all of its resources and data will be permanently deleted."
            footer={
              <>
                <SecondaryButton onClick={() => setConfirmingTeamDeletion(false)}>Cancel</SecondaryButton>
                <DangerButton className={`ms-3 ${form.processing ? 'opacity-25' : ''}`} disabled={form.processing} onClick={deleteTeam}>
                  Delete Team
                </DangerButton>
              </>
            }
          />
        </>
      }
    />
  );
};

export default DeleteTeamForm;
