// _TO_CONVERT_NOW/0example-react-recent/Pages/Teams/Partials/TeamMemberManager.tsx
import React, { useState, FormEventHandler } from 'react';
import { useForm, usePage, router } from '@inertiajs/react';
import ActionMessage from '@/Components/ActionMessage';
import ActionSection from '@/Components/ActionSection';
import ConfirmationModal from '@/Components/ConfirmationModal';
import DangerButton from '@/Components/DangerButton';
import DialogModal from '@/Components/DialogModal';
import FormSection from '@/Components/FormSection';
import InputError from '@/Components/InputError';
import InputLabel from '@/Components/InputLabel';
import PrimaryButton from '@/Components/PrimaryButton';
import SecondaryButton from '@/Components/SecondaryButton';
import SectionBorder from '@/Components/SectionBorder';
import TextInput from '@/Components/TextInput';

interface TeamMemberManagerProps {
  team: any;
  availableRoles: Array<any>;
  userPermissions: any;
}

const TeamMemberManager: React.FC<TeamMemberManagerProps> = ({ team, availableRoles, userPermissions }) => {
  const page: any = usePage();

  const [currentlyManagingRole, setCurrentlyManagingRole] = useState(false);
  const [managingRoleFor, setManagingRoleFor] = useState<any>(null);
  const [confirmingLeavingTeam, setConfirmingLeavingTeam] = useState(false);
  const [teamMemberBeingRemoved, setTeamMemberBeingRemoved] = useState<any>(null);

  const addTeamMemberForm = useForm({
    email: '',
    role: null,
  });

  const updateRoleForm = useForm({
    role: null,
  });

  const leaveTeamForm = useForm({});
  const removeTeamMemberForm = useForm({});

  const addTeamMember: FormEventHandler = (e) => {
    e.preventDefault();
    addTeamMemberForm.post(route('team-members.store', team), {
      errorBag: 'addTeamMember',
      preserveScroll: true,
      onSuccess: () => addTeamMemberForm.reset(),
    });
  };

  const cancelTeamInvitation = (invitation: any) => {
    router.delete(route('team-invitations.destroy', invitation), {
      preserveScroll: true,
    });
  };

  const manageRole = (teamMember: any) => {
    setManagingRoleFor(teamMember);
    updateRoleForm.setData('role', teamMember.membership.role);
    setCurrentlyManagingRole(true);
  };

  const updateRole: FormEventHandler = (e) => {
    e.preventDefault();
    updateRoleForm.put(route('team-members.update', [team, managingRoleFor]), {
      preserveScroll: true,
      onSuccess: () => setCurrentlyManagingRole(false),
    });
  };

  const confirmLeavingTeam = () => {
    setConfirmingLeavingTeam(true);
  };

  const leaveTeam: FormEventHandler = (e) => {
    e.preventDefault();
    leaveTeamForm.delete(route('team-members.destroy', [team, page.props.auth.user]));
  };

  const confirmTeamMemberRemoval = (teamMember: any) => {
    setTeamMemberBeingRemoved(teamMember);
  };

  const removeTeamMember: FormEventHandler = (e) => {
    e.preventDefault();
    removeTeamMemberForm.delete(route('team-members.destroy', [team, teamMemberBeingRemoved]), {
      errorBag: 'removeTeamMember',
      preserveScroll: true,
      preserveState: true,
      onSuccess: () => setTeamMemberBeingRemoved(null),
    });
  };

  const displayableRole = (role: string) => {
    return availableRoles.find((r) => r.key === role)?.name;
  };

  return (
    <div>
      {userPermissions.canAddTeamMembers && (
        <>
          <SectionBorder />

          <FormSection
            onSubmit={addTeamMember}
            title="Add Team Member"
            description="Add a new team member to your team, allowing them to collaborate with you."
            actions={
              <>
                <ActionMessage on={addTeamMemberForm.recentlySuccessful} className="me-3">
                  Added.
                </ActionMessage>
                <PrimaryButton className={addTeamMemberForm.processing ? 'opacity-25' : ''} disabled={addTeamMemberForm.processing}>
                  Add
                </PrimaryButton>
              </>
            }
          >
            <div className="col-span-6">
              <div className="max-w-xl text-sm text-gray-600 dark:text-gray-400">
                Please provide the email address of the person you would like to add to this team.
              </div>
            </div>

            <div className="col-span-6 sm:col-span-4">
              <InputLabel htmlFor="email" value="Email" />
              <TextInput
                id="email"
                type="email"
                value={addTeamMemberForm.data.email}
                onChange={(e) => addTeamMemberForm.setData('email', e.target.value)}
                className="block w-full mt-1"
              />
              <InputError message={addTeamMemberForm.errors.email} className="mt-2" />
            </div>

            {availableRoles.length > 0 && (
              <div className="col-span-6 lg:col-span-4">
                <InputLabel htmlFor="roles" value="Role" />
                <InputError message={addTeamMemberForm.errors.role} className="mt-2" />

                <div className="relative z-0 mt-1 border border-gray-200 rounded-lg cursor-pointer dark:border-gray-700">
                  {availableRoles.map((role, i) => (
                    <button
                      key={role.key}
                      type="button"
                      className={`relative px-4 py-3 inline-flex w-full rounded-lg focus:z-10 focus:outline-none focus:border-indigo-500 dark:focus:border-indigo-600 focus:ring-2 focus:ring-indigo-500 dark:focus:ring-indigo-600 ${
                        i > 0 ? 'border-t border-gray-200 dark:border-gray-700 focus:border-none rounded-t-none' : ''
                      } ${i !== availableRoles.length - 1 ? 'rounded-b-none' : ''}`}
                      onClick={() => addTeamMemberForm.setData('role', role.key)}
                    >
                      <div className={`${addTeamMemberForm.data.role && addTeamMemberForm.data.role !== role.key ? 'opacity-50' : ''}`}>
                        <div className="flex items-center">
                          <div
                            className={`text-sm text-gray-600 dark:text-gray-400 ${
                              addTeamMemberForm.data.role === role.key ? 'font-semibold' : ''
                            }`}
                          >
                            {role.name}
                          </div>
                          {addTeamMemberForm.data.role === role.key && (
                            <svg
                              className="w-5 h-5 text-green-400 ms-2"
                              xmlns="http://www.w3.org/2000/svg"
                              fill="none"
                              viewBox="0 0 24 24"
                              strokeWidth="1.5"
                              stroke="currentColor"
                            >
                              <path
                                strokeLinecap="round"
                                strokeLinejoin="round"
                                d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                              />
                            </svg>
                          )}
                        </div>
                        <div className="mt-2 text-xs text-gray-600 dark:text-gray-400 text-start">{role.description}</div>
                      </div>
                    </button>
                  ))}
                </div>
              </div>
            )}
          </FormSection>
        </>
      )}

      {team.team_invitations.length > 0 && userPermissions.canAddTeamMembers && (
        <>
          <SectionBorder />

          <ActionSection
            title="Pending Team Invitations"
            description="These people have been invited to your team and have been sent an invitation email. They may join the team by accepting the email invitation."
            content={
              <div className="space-y-6">
                {team.team_invitations.map((invitation: any) => (
                  <div key={invitation.id} className="flex items-center justify-between">
                    <div className="text-gray-600 dark:text-gray-400">{invitation.email}</div>
                    {userPermissions.canRemoveTeamMembers && (
                      <button
                        className="text-sm text-red-500 cursor-pointer ms-6 focus:outline-none"
                        onClick={() => cancelTeamInvitation(invitation)}
                      >
                        Cancel
                      </button>
                    )}
                  </div>
                ))}
              </div>
            }
          ></ActionSection>
        </>
      )}

      {team.users.length > 0 && (
        <>
          <SectionBorder />

          <ActionSection
            title="Team Members"
            description="All of the people that are part of this team."
            content={
              <div className="space-y-6">
                {team.users.map((user: any) => (
                  <div key={user.id} className="flex items-center justify-between">
                    <div className="flex items-center">
                      <img className="object-cover w-8 h-8 rounded-full" src={user.profile_photo_url} alt={user.name} />
                      <div className="ms-4 dark:text-white">{user.name}</div>
                    </div>
                    <div className="flex items-center">
                      {userPermissions.canUpdateTeamMembers && availableRoles.length > 0 ? (
                        <button className="text-sm text-gray-400 underline ms-2" onClick={() => manageRole(user)}>
                          {displayableRole(user.membership.role)}
                        </button>
                      ) : (
                        <div className="text-sm text-gray-400 ms-2">{displayableRole(user.membership.role)}</div>
                      )}
                      {page.props.auth.user.id === user.id ? (
                        <button className="text-sm text-red-500 cursor-pointer ms-6" onClick={confirmLeavingTeam}>
                          Leave
                        </button>
                      ) : (
                        userPermissions.canRemoveTeamMembers && (
                          <button className="text-sm text-red-500 cursor-pointer ms-6" onClick={() => confirmTeamMemberRemoval(user)}>
                            Remove
                          </button>
                        )
                      )}
                    </div>
                  </div>
                ))}
              </div>
            }
          ></ActionSection>
        </>
      )}

      <DialogModal
        show={currentlyManagingRole}
        onClose={() => setCurrentlyManagingRole(false)}
        title="Manage Role"
        content={
          managingRoleFor && (
            <div className="relative z-0 mt-1 border border-gray-200 rounded-lg cursor-pointer dark:border-gray-700">
              {availableRoles.map((role, i) => (
                <button
                  key={role.key}
                  type="button"
                  className={`relative px-4 py-3 inline-flex w-full rounded-lg focus:z-10 focus:outline-none focus:border-indigo-500 dark:focus:border-indigo-600 focus:ring-2 focus:ring-indigo-500 dark:focus:ring-indigo-600 ${
                    i > 0 ? 'border-t border-gray-200 dark:border-gray-700 focus:border-none rounded-t-none' : ''
                  } ${i !== availableRoles.length - 1 ? 'rounded-b-none' : ''}`}
                  onClick={() => updateRoleForm.setData('role', role.key)}
                >
                  <div className={`${updateRoleForm.data.role && updateRoleForm.data.role !== role.key ? 'opacity-50' : ''}`}>
                    <div className="flex items-center">
                      <div
                        className={`text-sm text-gray-600 dark:text-gray-400 ${
                          updateRoleForm.data.role === role.key ? 'font-semibold' : ''
                        }`}
                      >
                        {role.name}
                      </div>
                      {updateRoleForm.data.role === role.key && (
                        <svg
                          className="w-5 h-5 text-green-400 ms-2"
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 24 24"
                          strokeWidth="1.5"
                          stroke="currentColor"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                          />
                        </svg>
                      )}
                    </div>
                    <div className="mt-2 text-xs text-gray-600 dark:text-gray-400">{role.description}</div>
                  </div>
                </button>
              ))}
            </div>
          )
        }
        footer={
          <>
            <SecondaryButton onClick={() => setCurrentlyManagingRole(false)}>Cancel</SecondaryButton>
            <PrimaryButton
              className={updateRoleForm.processing ? 'ms-3 opacity-25' : 'ms-3'}
              disabled={updateRoleForm.processing}
              onClick={updateRole}
            >
              Save
            </PrimaryButton>
          </>
        }
      />

      <ConfirmationModal
        show={confirmingLeavingTeam}
        onClose={() => setConfirmingLeavingTeam(false)}
        title="Leave Team"
        content="Are you sure you would like to leave this team?"
        footer={
          <>
            <SecondaryButton onClick={() => setConfirmingLeavingTeam(false)}>Cancel</SecondaryButton>
            <DangerButton
              className={leaveTeamForm.processing ? 'ms-3 opacity-25' : 'ms-3'}
              disabled={leaveTeamForm.processing}
              onClick={leaveTeam}
            >
              Leave
            </DangerButton>
          </>
        }
      />

      <ConfirmationModal
        show={!!teamMemberBeingRemoved}
        onClose={() => setTeamMemberBeingRemoved(null)}
        title="Remove Team Member"
        content="Are you sure you would like to remove this person from the team?"
        footer={
          <>
            <SecondaryButton onClick={() => setTeamMemberBeingRemoved(null)}>Cancel</SecondaryButton>
            <DangerButton
              className={removeTeamMemberForm.processing ? 'ms-3 opacity-25' : 'ms-3'}
              disabled={removeTeamMemberForm.processing}
              onClick={removeTeamMember}
            >
              Remove
            </DangerButton>
          </>
        }
      />
    </div>
  );
};

export default TeamMemberManager;

// _TO_CONVERT_NOW/0example-react-recent/Pages/Teams/Partials/TeamMemberManager.vue
<script lang="ts" setup>
import { ref } from 'vue';
import { router, useForm, usePage } from '@inertiajs/vue3';
import ActionMessage from '@/Components/ActionMessage.vue';
import ActionSection from '@/Components/ActionSection.vue';
import ConfirmationModal from '@/Components/ConfirmationModal.vue';
import DangerButton from '@/Components/DangerButton.vue';
import DialogModal from '@/Components/DialogModal.vue';
import FormSection from '@/Components/FormSection.vue';
import InputError from '@/Components/InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import SecondaryButton from '@/Components/SecondaryButton.vue';
import SectionBorder from '@/Components/SectionBorder.vue';
import TextInput from '@/Components/TextInput.vue';

const props = defineProps({
  team: Object,
  availableRoles: Array,
  userPermissions: Object,
});

const page = usePage();

const addTeamMemberForm = useForm({
  email: '',
  role: null,
});

const updateRoleForm = useForm({
  role: null,
});

const leaveTeamForm = useForm({});
const removeTeamMemberForm = useForm({});

const currentlyManagingRole = ref(false);
const managingRoleFor = ref(null);
const confirmingLeavingTeam = ref(false);
const teamMemberBeingRemoved = ref(null);

const addTeamMember = () => {
  addTeamMemberForm.post(route('team-members.store', props.team), {
    errorBag: 'addTeamMember',
    preserveScroll: true,
    onSuccess: () => addTeamMemberForm.reset(),
  });
};

const cancelTeamInvitation = (invitation) => {
  router.delete(route('team-invitations.destroy', invitation), {
    preserveScroll: true,
  });
};

const manageRole = (teamMember) => {
  managingRoleFor.value = teamMember;
  updateRoleForm.role = teamMember.membership.role;
  currentlyManagingRole.value = true;
};

const updateRole = () => {
  updateRoleForm.put(route('team-members.update', [props.team, managingRoleFor.value]), {
    preserveScroll: true,
    onSuccess: () => (currentlyManagingRole.value = false),
  });
};

const confirmLeavingTeam = () => {
  confirmingLeavingTeam.value = true;
};

const leaveTeam = () => {
  leaveTeamForm.delete(route('team-members.destroy', [props.team, page.props.auth.user]));
};

const confirmTeamMemberRemoval = (teamMember) => {
  teamMemberBeingRemoved.value = teamMember;
};

const removeTeamMember = () => {
  removeTeamMemberForm.delete(route('team-members.destroy', [props.team, teamMemberBeingRemoved.value]), {
    errorBag: 'removeTeamMember',
    preserveScroll: true,
    preserveState: true,
    onSuccess: () => (teamMemberBeingRemoved.value = null),
  });
};

const displayableRole = (role) => {
  return props.availableRoles.find((r) => r.key === role).name;
};
</script>

<template>
  <div>
    <div v-if="userPermissions.canAddTeamMembers">
      <SectionBorder />

      <!-- Add Team Member -->
      <FormSection @submitted="addTeamMember">
        <template #title> Add Team Member </template>

        <template #description> Add a new team member to your team, allowing them to collaborate with you. </template>

        <template #form>
          <div class="col-span-6">
            <div class="max-w-xl text-sm text-gray-600">
              Please provide the email address of the person you would like to add to this team.
            </div>
          </div>

          <!-- Member Email -->
          <div class="col-span-6 sm:col-span-4">
            <InputLabel for="email" value="Email" />
            <TextInput id="email" v-model="addTeamMemberForm.email" type="email" class="mt-1 block w-full" />
            <InputError :message="addTeamMemberForm.errors.email" class="mt-2" />
          </div>

          <!-- Role -->
          <div v-if="availableRoles.length > 0" class="col-span-6 lg:col-span-4">
            <InputLabel for="roles" value="Role" />
            <InputError :message="addTeamMemberForm.errors.role" class="mt-2" />

            <div class="relative z-0 mt-1 border border-gray-200 rounded-lg cursor-pointer">
              <button
                v-for="(role, i) in availableRoles"
                :key="role.key"
                type="button"
                class="relative px-4 py-3 inline-flex w-full rounded-lg focus:z-10 focus:outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500"
                :class="{
                  'border-t border-gray-200 focus:border-none rounded-t-none': i > 0,
                  'rounded-b-none': i != Object.keys(availableRoles).length - 1,
                }"
                @click="addTeamMemberForm.role = role.key"
              >
                <div :class="{ 'opacity-50': addTeamMemberForm.role && addTeamMemberForm.role != role.key }">
                  <!-- Role Name -->
                  <div class="flex items-center">
                    <div class="text-sm text-gray-600" :class="{ 'font-semibold': addTeamMemberForm.role == role.key }">
                      {{ role.name }}
                    </div>

                    <svg
                      v-if="addTeamMemberForm.role == role.key"
                      class="ms-2 h-5 w-5 text-green-400"
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke-width="1.5"
                      stroke="currentColor"
                    >
                      <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                      />
                    </svg>
                  </div>

                  <!-- Role Description -->
                  <div class="mt-2 text-xs text-gray-600 text-start">
                    {{ role.description }}
                  </div>
                </div>
              </button>
            </div>
          </div>
        </template>

        <template #actions>
          <ActionMessage :on="addTeamMemberForm.recentlySuccessful" class="me-3"> Added. </ActionMessage>

          <PrimaryButton :class="{ 'opacity-25': addTeamMemberForm.processing }" :disabled="addTeamMemberForm.processing">
            Add
          </PrimaryButton>
        </template>
      </FormSection>
    </div>

    <div v-if="team.team_invitations.length > 0 && userPermissions.canAddTeamMembers">
      <SectionBorder />

      <!-- Team Member Invitations -->
      <ActionSection class="mt-10 sm:mt-0">
        <template #title> Pending Team Invitations </template>

        <template #description>
          These people have been invited to your team and have been sent an invitation email. They may join the team by accepting the email
          invitation.
        </template>

        <!-- Pending Team Member Invitation List -->
        <template #content>
          <div class="space-y-6">
            <div v-for="invitation in team.team_invitations" :key="invitation.id" class="flex items-center justify-between">
              <div class="text-gray-600">
                {{ invitation.email }}
              </div>

              <div class="flex items-center">
                <!-- Cancel Team Invitation -->
                <button
                  v-if="userPermissions.canRemoveTeamMembers"
                  class="cursor-pointer ms-6 text-sm text-red-500 focus:outline-none"
                  @click="cancelTeamInvitation(invitation)"
                >
                  Cancel
                </button>
              </div>
            </div>
          </div>
        </template>
      </ActionSection>
    </div>

    <div v-if="team.users.length > 0">
      <SectionBorder />

      <!-- Manage Team Members -->
      <ActionSection class="mt-10 sm:mt-0">
        <template #title> Team Members </template>

        <template #description> All of the people that are part of this team. </template>

        <!-- Team Member List -->
        <template #content>
          <div class="space-y-6">
            <div v-for="user in team.users" :key="user.id" class="flex items-center justify-between">
              <div class="flex items-center">
                <img class="w-8 h-8 rounded-full object-cover" :src="user.profile_photo_url" :alt="user.name" />
                <div class="ms-4">
                  {{ user.name }}
                </div>
              </div>

              <div class="flex items-center">
                <!-- Manage Team Member Role -->
                <button
                  v-if="userPermissions.canUpdateTeamMembers && availableRoles.length"
                  class="ms-2 text-sm text-gray-400 underline"
                  @click="manageRole(user)"
                >
                  {{ displayableRole(user.membership.role) }}
                </button>

                <div v-else-if="availableRoles.length" class="ms-2 text-sm text-gray-400">
                  {{ displayableRole(user.membership.role) }}
                </div>

                <!-- Leave Team -->
                <button
                  v-if="$page.props.auth.user.id === user.id"
                  class="cursor-pointer ms-6 text-sm text-red-500"
                  @click="confirmLeavingTeam"
                >
                  Leave
                </button>

                <!-- Remove Team Member -->
                <button
                  v-else-if="userPermissions.canRemoveTeamMembers"
                  class="cursor-pointer ms-6 text-sm text-red-500"
                  @click="confirmTeamMemberRemoval(user)"
                >
                  Remove
                </button>
              </div>
            </div>
          </div>
        </template>
      </ActionSection>
    </div>

    <!-- Role Management Modal -->
    <DialogModal :show="currentlyManagingRole" @close="currentlyManagingRole = false">
      <template #title> Manage Role </template>

      <template #content>
        <div v-if="managingRoleFor">
          <div class="relative z-0 mt-1 border border-gray-200 rounded-lg cursor-pointer">
            <button
              v-for="(role, i) in availableRoles"
              :key="role.key"
              type="button"
              class="relative px-4 py-3 inline-flex w-full rounded-lg focus:z-10 focus:outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500"
              :class="{
                'border-t border-gray-200 focus:border-none rounded-t-none': i > 0,
                'rounded-b-none': i !== Object.keys(availableRoles).length - 1,
              }"
              @click="updateRoleForm.role = role.key"
            >
              <div :class="{ 'opacity-50': updateRoleForm.role && updateRoleForm.role !== role.key }">
                <!-- Role Name -->
                <div class="flex items-center">
                  <div class="text-sm text-gray-600" :class="{ 'font-semibold': updateRoleForm.role === role.key }">
                    {{ role.name }}
                  </div>

                  <svg
                    v-if="updateRoleForm.role == role.key"
                    class="ms-2 h-5 w-5 text-green-400"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke-width="1.5"
                    stroke="currentColor"
                  >
                    <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                </div>

                <!-- Role Description -->
                <div class="mt-2 text-xs text-gray-600">
                  {{ role.description }}
                </div>
              </div>
            </button>
          </div>
        </div>
      </template>

      <template #footer>
        <SecondaryButton @click="currentlyManagingRole = false"> Cancel </SecondaryButton>

        <PrimaryButton
          class="ms-3"
          :class="{ 'opacity-25': updateRoleForm.processing }"
          :disabled="updateRoleForm.processing"
          @click="updateRole"
        >
          Save
        </PrimaryButton>
      </template>
    </DialogModal>

    <!-- Leave Team Confirmation Modal -->
    <ConfirmationModal :show="confirmingLeavingTeam" @close="confirmingLeavingTeam = false">
      <template #title> Leave Team </template>

      <template #content> Are you sure you would like to leave this team? </template>

      <template #footer>
        <SecondaryButton @click="confirmingLeavingTeam = false"> Cancel </SecondaryButton>

        <DangerButton
          class="ms-3"
          :class="{ 'opacity-25': leaveTeamForm.processing }"
          :disabled="leaveTeamForm.processing"
          @click="leaveTeam"
        >
          Leave
        </DangerButton>
      </template>
    </ConfirmationModal>

    <!-- Remove Team Member Confirmation Modal -->
    <ConfirmationModal :show="teamMemberBeingRemoved" @close="teamMemberBeingRemoved = null">
      <template #title> Remove Team Member </template>

      <template #content> Are you sure you would like to remove this person from the team? </template>

      <template #footer>
        <SecondaryButton @click="teamMemberBeingRemoved = null"> Cancel </SecondaryButton>

        <DangerButton
          class="ms-3"
          :class="{ 'opacity-25': removeTeamMemberForm.processing }"
          :disabled="removeTeamMemberForm.processing"
          @click="removeTeamMember"
        >
          Remove
        </DangerButton>
      </template>
    </ConfirmationModal>
  </div>
</template>
