// _TO_CONVERT_NOW/0example-react-recent/Pages/Teams/Partials/UpdateTeamNameForm.vue
<script lang="ts" setup>
import { useForm } from '@inertiajs/vue3';
import ActionMessage from '@/Components/ActionMessage.vue';
import FormSection from '@/Components/FormSection.vue';
import InputError from '@/Components/InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import TextInput from '@/Components/TextInput.vue';

const props = defineProps({
  team: Object,
  permissions: Object,
});

const form = useForm({
  name: props.team.name,
});

const updateTeamName = () => {
  form.put(route('teams.update', props.team), {
    errorBag: 'updateTeamName',
    preserveScroll: true,
  });
};
</script>

<template>
  <FormSection @submitted="updateTeamName">
    <template #title> Team Name </template>

    <template #description> The team's name and owner information. </template>

    <template #form>
      <!-- Team Owner Information -->
      <div class="col-span-6">
        <InputLabel value="Team Owner" />

        <div class="flex items-center mt-2">
          <img class="w-12 h-12 rounded-full object-cover" :src="team.owner.profile_photo_url" :alt="team.owner.name" />

          <div class="ms-4 leading-tight">
            <div class="text-gray-900">{{ team.owner.name }}</div>
            <div class="text-gray-700 text-sm">
              {{ team.owner.email }}
            </div>
          </div>
        </div>
      </div>

      <!-- Team Name -->
      <div class="col-span-6 sm:col-span-4">
        <InputLabel for="name" value="Team Name" />

        <TextInput id="name" v-model="form.name" type="text" class="mt-1 block w-full" :disabled="!permissions.canUpdateTeam" />

        <InputError :message="form.errors.name" class="mt-2" />
      </div>
    </template>

    <template v-if="permissions.canUpdateTeam" #actions>
      <ActionMessage :on="form.recentlySuccessful" class="me-3"> Saved. </ActionMessage>

      <PrimaryButton :class="{ 'opacity-25': form.processing }" :disabled="form.processing"> Save </PrimaryButton>
    </template>
  </FormSection>
</template>

// _TO_CONVERT_NOW/0example-react-recent/Pages/Teams/Partials/UpdateTeamNameForm.tsx
import React, { FormEventHandler } from 'react';
import { useForm } from '@inertiajs/react';
import ActionMessage from '@/Components/ActionMessage';
import FormSection from '@/Components/FormSection';
import InputError from '@/Components/InputError';
import InputLabel from '@/Components/InputLabel';
import PrimaryButton from '@/Components/PrimaryButton';
import TextInput from '@/Components/TextInput';

interface UpdateTeamNameFormProps {
  team: {
    id: number;
    name: string;
    owner: {
      name: string;
      email: string;
      profile_photo_url: string;
    };
  };
  permissions: {
    canUpdateTeam: boolean;
  };
}

const UpdateTeamNameForm: React.FC<UpdateTeamNameFormProps> = ({ team, permissions }) => {
  const form = useForm({
    name: team.name,
  });

  const updateTeamName: FormEventHandler = (e) => {
    e.preventDefault();
    form.put(route('teams.update', team), {
      errorBag: 'updateTeamName',
      preserveScroll: true,
    });
  };

  return (
    <FormSection
      onSubmit={updateTeamName}
      title="Team Name"
      description="The team's name and owner information."
      actions={
        permissions.canUpdateTeam && (
          <>
            <ActionMessage on={form.recentlySuccessful} className="me-3">
              Saved.
            </ActionMessage>
            <PrimaryButton className={form.processing ? 'opacity-25' : ''} disabled={form.processing}>
              Save
            </PrimaryButton>
          </>
        )
      }
    >
      <div className="col-span-6">
        <InputLabel value="Team Owner" />
        <div className="flex items-center mt-2">
          <img className="object-cover w-12 h-12 rounded-full" src={team.owner.profile_photo_url} alt={team.owner.name} />
          <div className="leading-tight ms-4">
            <div className="text-gray-900 dark:text-white">{team.owner.name}</div>
            <div className="text-sm text-gray-700 dark:text-gray-300">{team.owner.email}</div>
          </div>
        </div>
      </div>

      <div className="col-span-6 sm:col-span-4">
        <InputLabel htmlFor="name" value="Team Name" />
        <TextInput
          id="name"
          value={form.data.name}
          onChange={(e) => form.setData('name', e.target.value)}
          type="text"
          className="block w-full mt-1"
          disabled={!permissions.canUpdateTeam}
        />
        <InputError message={form.errors.name} className="mt-2" />
      </div>
    </FormSection>
  );
};

export default UpdateTeamNameForm;
