// _TO_CONVERT_NOW/0example-react/Pages/TermsOfService.vue
<script lang="ts" setup>
import { Head } from '@inertiajs/vue3';
import AuthenticationCardLogo from '@/Components/AuthenticationCardLogo.vue';

defineProps({
  terms: String,
});
</script>

<template>
  <Head title="Terms of Service" />

  <div class="font-sans text-gray-900 antialiased">
    <div class="pt-4 bg-gray-100">
      <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
        <div>
          <AuthenticationCardLogo />
        </div>

        <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose" v-html="terms" />
      </div>
    </div>
  </div>
</template>

// _TO_CONVERT_NOW/0example-react/Pages/TermsOfService.tsx
import React from 'react';
import { Head } from '@inertiajs/react';
import AuthenticationCardLogo from '@/Components/AuthenticationCardLogo';

interface TermsOfServiceProps {
  terms: string;
}

const TermsOfService: React.FC<TermsOfServiceProps> = ({ terms }) => {
  return (
    <>
      <Head title="Terms of Service" />

      <div className="font-sans antialiased text-gray-900 dark:text-gray-100">
        <div className="pt-4 bg-gray-100 dark:bg-gray-900">
          <div className="flex flex-col items-center min-h-screen pt-6 sm:pt-0">
            <div>
              <AuthenticationCardLogo />
            </div>

            <div
              className="w-full p-6 mt-6 overflow-hidden prose bg-white shadow-md sm:max-w-2xl dark:bg-gray-800 sm:rounded-lg dark:prose-invert"
              dangerouslySetInnerHTML={{ __html: terms }}
            />
          </div>
        </div>
      </div>
    </>
  );
};

export default TermsOfService;
