// apps/knowii/src/Pages/TermsOfService.tsx
import React from 'react';
import PageHeader from '@/Components/PageHeader';
import { PageContentWrapper } from '@/Components/PageContentWrapper';
import { Head } from '@inertiajs/react';
import FooterGuest from '@/Components/FooterGuest';

interface Props {
  terms: string;
}

export default function TermsOfService(props: Props) {
  return (
    <>
      <Head title="Terms of Service" />

      <div className="bg-gray-50 full-page">
        <PageHeader
          compact={true}
          addLinkOnLogo={true}
          showDashboardButton={false}
          showLogoutButton={false}
          showLoginButton={false}
          showRegisterButton={false}
        />

        <PageContentWrapper>
          <div className="flex flex-col items-center">
            <div
              className="min-w-full md:min-w-[75%] xl:min-w-[50%] p-6 mt-6 overflow-hidden prose bg-white shadow-md sm:max-w-2xl sm:rounded-lg"
              dangerouslySetInnerHTML={{ __html: props.terms }}
            />
          </div>
          <FooterGuest />
        </PageContentWrapper>
      </div>
    </>
  );
}

// _TO_CONVERT_NOW/0example-react/Pages/TermsOfService.vue
<script lang="ts" setup>
import { Head } from '@inertiajs/vue3';
import AuthenticationCardLogo from '@/Components/AuthenticationCardLogo.vue';

defineProps({
  terms: String,
});
</script>

<template>
  <Head title="Terms of Service" />

  <div class="font-sans text-gray-900 antialiased">
    <div class="pt-4 bg-gray-100">
      <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
        <div>
          <AuthenticationCardLogo />
        </div>

        <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose" v-html="terms" />
      </div>
    </div>
  </div>
</template>
