// _TO_CONVERT_NOW/0example-react-longstanding/Pages/API/Index.tsx
import React from 'react';
import APITokenManager from '@/Pages/API/Partials/APITokenManager';
import AppLayout from '@/Layouts/AppLayout';
import { ApiToken } from '@/types';

interface Props {
  tokens: ApiToken[];
  availablePermissions: string[];
  defaultPermissions: string[];
}

export default function ApiTokenIndex({ tokens, availablePermissions, defaultPermissions }: Props) {
  return (
    <AppLayout title={'API Tokens'} renderHeader={() => <h2 className="font-semibold text-xl text-gray-800 leading-tight">API Tokens</h2>}>
      <div>
        <div className="max-w-7xl mx-auto py-10 sm:px-6 lg:px-8">
          <APITokenManager tokens={tokens} availablePermissions={availablePermissions} defaultPermissions={defaultPermissions} />
        </div>
      </div>
    </AppLayout>
  );
}

// _TO_CONVERT_NOW/0example-react-recent/Pages/API/Index.vue
<script lang="ts" setup>
import ApiTokenManager from '@/Pages/API/Partials/ApiTokenManager.vue';
import AppLayout from '@/Layouts/AppLayout.vue';

defineProps({
  tokens: Array,
  availablePermissions: Array,
  defaultPermissions: Array,
});
</script>

<template>
  <AppLayout title="API Tokens">
    <template #header>
      <h2 class="font-semibold text-xl text-gray-800 leading-tight">API Tokens</h2>
    </template>

    <div>
      <div class="max-w-7xl mx-auto py-10 sm:px-6 lg:px-8">
        <ApiTokenManager :tokens="tokens" :available-permissions="availablePermissions" :default-permissions="defaultPermissions" />
      </div>
    </div>
  </AppLayout>
</template>
