// _TO_CONVERT_NOW/0example-react/Pages/API/Index.tsx
import React from 'react';
import AppLayout from '@/Layouts/AppLayout';
import ApiTokenManager from '@/Pages/API/Partials/ApiTokenManager';

interface IndexProps {
  tokens: Array<any>;
  availablePermissions: Array<string>;
  defaultPermissions: Array<string>;
}

const Index: React.FC<IndexProps> = ({ tokens, availablePermissions, defaultPermissions }) => {
  return (
    <AppLayout
      title="API Tokens"
      header={<div className="text-xl font-semibold leading-tight text-gray-800 dark:text-gray-200">API Tokens</div>}
    >
      <div>
        <div className="py-10 mx-auto max-w-7xl sm:px-6 lg:px-8">
          <ApiTokenManager tokens={tokens} availablePermissions={availablePermissions} defaultPermissions={defaultPermissions} />
        </div>
      </div>
    </AppLayout>
  );
};

export default Index;

// _TO_CONVERT_NOW/0example-react-recent/Pages/API/Index.vue
<script lang="ts" setup>
import ApiTokenManager from '@/Pages/API/Partials/ApiTokenManager.vue';
import AppLayout from '@/Layouts/AppLayout.vue';

defineProps({
  tokens: Array,
  availablePermissions: Array,
  defaultPermissions: Array,
});
</script>

<template>
  <AppLayout title="API Tokens">
    <template #header>
      <h2 class="font-semibold text-xl text-gray-800 leading-tight">API Tokens</h2>
    </template>

    <div>
      <div class="max-w-7xl mx-auto py-10 sm:px-6 lg:px-8">
        <ApiTokenManager :tokens="tokens" :available-permissions="availablePermissions" :default-permissions="defaultPermissions" />
      </div>
    </div>
  </AppLayout>
</template>
