// _TO_CONVERT_NOW/0example-react-recent/Components/ActionMessage.vue
<script lang="ts" setup>
defineProps({
  on: Boolean,
});
</script>

<template>
  <div>
    <transition leave-active-class="transition ease-in duration-1000" leave-from-class="opacity-100" leave-to-class="opacity-0">
      <div v-show="on" class="text-sm text-gray-600">
        <slot />
      </div>
    </transition>
  </div>
</template>

// apps/knowii/src/Components/ActionMessage.tsx
import { Transition } from '@headlessui/react';
import React, { PropsWithChildren } from 'react';

interface Props {
  on: boolean;
  className?: string;
}

export default function ActionMessage({ on, className, children }: PropsWithChildren<Props>) {
  return (
    <div className={className}>
      <Transition show={on} leave="transition ease-in duration-1000" leave-from-class="opacity-100" leaveTo="opacity-0">
        <div className="text-sm text-gray-600">{children}</div>
      </Transition>
    </div>
  );
}
