// _TO_CONVERT_NOW/0example-react-recent/Pages/Teams/Create.tsx
import React from 'react';
import AppLayout from '@/Layouts/AppLayout';
import CreateTeamForm from '@/Pages/Teams/Partials/CreateTeamForm';

const CreateTeam: React.FC = () => {
  return (
    <AppLayout
      title="Create Team"
      header={<div className="text-xl font-semibold leading-tight text-gray-800 dark:text-gray-200">Create Team</div>}
    >
      <div>
        <div className="py-10 mx-auto max-w-7xl sm:px-6 lg:px-8">
          <CreateTeamForm />
        </div>
      </div>
    </AppLayout>
  );
};

export default CreateTeam;

// _TO_CONVERT_NOW/0example-react-recent/Pages/Teams/Create.vue
<script lang="ts" setup>
import AppLayout from '@/Layouts/AppLayout.vue';
import CreateTeamForm from '@/Pages/Teams/Partials/CreateTeamForm.vue';
</script>

<template>
  <AppLayout title="Create Team">
    <template #header>
      <h2 class="font-semibold text-xl text-gray-800 leading-tight">Create Team</h2>
    </template>

    <div>
      <div class="max-w-7xl mx-auto py-10 sm:px-6 lg:px-8">
        <CreateTeamForm />
      </div>
    </div>
  </AppLayout>
</template>
