// _TO_CONVERT_NOW/0example-react-recent/Pages/Teams/Create.vue
<script lang="ts" setup>
import AppLayout from '@/Layouts/AppLayout.vue';
import CreateTeamForm from '@/Pages/Teams/Partials/CreateTeamForm.vue';
</script>

<template>
  <AppLayout title="Create Team">
    <template #header>
      <h2 class="font-semibold text-xl text-gray-800 leading-tight">Create Team</h2>
    </template>

    <div>
      <div class="max-w-7xl mx-auto py-10 sm:px-6 lg:px-8">
        <CreateTeamForm />
      </div>
    </div>
  </AppLayout>
</template>

// apps/knowii/src/Pages/Communities/Create.tsx
import AppLayout from '@/Layouts/AppLayout';

export default function CreateCommunity() {
  return (
    <AppLayout title="New Community" header={<h1 className="text-xl font-semibold leading-tight text-white">New Community</h1>}>
      <div className="flex flex-col w-full items-center">Yay, let's create a new community</div>
    </AppLayout>
  );
}
