// _TO_CONVERT_NOW/0example-react/Pages/Profile/Show.vue
    <div>
      <div class="max-w-7xl mx-auto py-10 sm:px-6 lg:px-8">
        <div v-if="$page.props.jetstream.canUpdateProfileInformation">
          <UpdateProfileInformationForm :user="$page.props.auth.user" />

          <SectionBorder />
        </div>

        <div v-if="$page.props.jetstream.canUpdatePassword">
          <UpdatePasswordForm class="mt-10 sm:mt-0" />

          <SectionBorder />
        </div>

        <div v-if="$page.props.jetstream.canManageTwoFactorAuthentication">
          <TwoFactorAuthenticationForm :requires-confirmation="confirmsTwoFactorAuthentication" class="mt-10 sm:mt-0" />

          <SectionBorder />
        </div>

        <LogoutOtherBrowserSessionsForm :sessions="sessions" class="mt-10 sm:mt-0" />

        <template v-if="$page.props.jetstream.hasAccountDeletionFeatures">
          <SectionBorder />

          <DeleteUserForm class="mt-10 sm:mt-0" />
        </template>
      </div>

// _TO_CONVERT_NOW/0example-react/Pages/Profile/Show.tsx

              <UpdateProfileInformationForm user={auth.user} jetstream={jetstream} />
              <SectionBorder />




          {jetstream.canUpdatePassword && (
            <>
              <div className="mt-10 sm:mt-0">
                <UpdatePasswordForm />
              </div>
              <SectionBorder />
            </>
          )}

          {jetstream.canManageTwoFactorAuthentication && (
            <>
              <div className="mt-10 sm:mt-0">
                <TwoFactorAuthenticationForm requiresConfirmation={confirmsTwoFactorAuthentication} />
              </div>
              <SectionBorder />
            </>
          )}

          <div className="mt-10 sm:mt-0">
            <LogoutOtherBrowserSessionsForm sessions={sessions} />
          </div>

          {jetstream.hasAccountDeletionFeatures && (
            <>
              <SectionBorder />
              <DeleteUserForm className="mt-10 sm:mt-0" />
            </>
          )}
        </div>
      </div>
    </AppLayout>
  );
};

export default Profile;
