// _TO_CONVERT_NOW/0example-react-recent/Pages/Teams/Create.vue
<script lang="ts" setup>
import AppLayout from '@/Layouts/AppLayout.vue';
import CreateTeamForm from '@/Pages/Teams/Partials/CreateTeamForm.vue';
</script>

<template>
  <AppLayout title="Create Team">
    <template #header>
      <h2 class="font-semibold text-xl text-gray-800 leading-tight">Create Team</h2>
    </template>

    <div>
      <div class="max-w-7xl mx-auto py-10 sm:px-6 lg:px-8">
        <CreateTeamForm />
      </div>
    </div>
  </AppLayout>
</template>

// _TO_CONVERT_NOW/0example-react-longstanding/Pages/Teams/Create.tsx
import CreateTeamForm from '@/Pages/Teams/Partials/CreateTeamForm';
import AppLayout from '@/Layouts/AppLayout';
import React from 'react';

export default function Create() {
  return (
    <AppLayout title="Create Team" renderHeader={() => <h2 className="font-semibold text-xl text-gray-800 leading-tight">Create Team</h2>}>
      <div>
        <div className="max-w-7xl mx-auto py-10 sm:px-6 lg:px-8">
          <CreateTeamForm />
        </div>
      </div>
    </AppLayout>
  );
}
