// _TO_CONVERT_NOW/0example-react-recent/Components/ActionMessage.tsx
import { useEffect, useState, ReactNode } from 'react';

interface MyComponentProps {
  on: boolean;
  children: ReactNode;
  className?: string;
}

const MyComponent: React.FC<MyComponentProps> = ({ on, children, className }) => {
  const [visible, setVisible] = useState(on);

  useEffect(() => {
    setVisible(on);
  }, [on]);

  return (
    <div className={className}>
      <div
        className={`transition ease-in duration-1000 ${visible ? 'opacity-100' : 'opacity-0'} text-sm text-gray-600 dark:text-gray-400`}
        style={{ display: visible ? 'block' : 'none' }}
      >
        {children}
      </div>
    </div>
  );
};

export default MyComponent;

// _TO_CONVERT_NOW/0example-react-recent/Components/ActionMessage.vue
<script lang="ts" setup>
defineProps({
  on: Boolean,
});
</script>

<template>
  <div>
    <transition leave-active-class="transition ease-in duration-1000" leave-from-class="opacity-100" leave-to-class="opacity-0">
      <div v-show="on" class="text-sm text-gray-600">
        <slot />
      </div>
    </transition>
  </div>
</template>
