// _TO_CONVERT_NOW/0example-react-recent/Components/ConfirmsPassword.tsx
import React, { useState, useRef, type FormEventHandler } from 'react';
import axios from 'axios';
import { useForm } from '@inertiajs/react';
import DialogModal from './DialogModal';
import InputError from './InputError';
import PrimaryButton from './PrimaryButton';
import SecondaryButton from './SecondaryButton';
import TextInput from './TextInput';

const ConfirmPasswordModal = ({
  title = 'Confirm Password',
  content = 'For your security, please confirm your password to continue.',
  button = 'Confirm',
  onConfirmed,
  children,
}: any) => {
  const [confirmingPassword, setConfirmingPassword] = useState(false);
  const passwordInput: any = useRef(null);

  const form = useForm({
    password: '',
    error: '',
    processing: false,
  });

  const startConfirmingPassword: FormEventHandler = (e) => {
    axios.get(route('password.confirmation')).then((response) => {
      if (response.data.confirmed) {
        onConfirmed(e);
      } else {
        setConfirmingPassword(true);
        setTimeout(() => passwordInput.current.focus(), 250);
      }
    });
  };

  const confirmPassword: FormEventHandler = (e) => {
    e.preventDefault();
    form.setData('processing', true);

    axios
      .post(route('password.confirm'), {
        password: form.data.password,
      })
      .then(() => {
        form.setData('processing', false);
        closeModal();
        onConfirmed(e);
      })
      .catch((error) => {
        form.setData('processing', false);
        form.setData('error', error.response.data.errors.password[0]);
        passwordInput.current.focus();
      });
  };

  const closeModal = () => {
    setConfirmingPassword(false);
    form.setData('password', '');
    form.setData('error', '');
  };

  return (
    <span>
      <span onClick={startConfirmingPassword}>{children}</span>

      <DialogModal
        show={confirmingPassword}
        onClose={closeModal}
        title={<h2>{title}</h2>}
        content={
          <>
            <p>{content}</p>
            <div className="mt-4">
              <TextInput
                ref={passwordInput}
                value={form.data.password}
                onChange={(e) => form.setData('password', e.target.value)}
                type="password"
                className="block w-3/4 mt-1"
                placeholder="Password"
                autoComplete="current-password"
                onKeyUp={(e) => {
                  if (e.key === 'Enter') confirmPassword(e);
                }}
              />
              <InputError message={form.data.error} className="mt-2" />
            </div>
            <div className="mt-4">
              <SecondaryButton onClick={closeModal}>Cancel</SecondaryButton>
              <PrimaryButton
                className={`ms-3 ${form.data.processing ? 'opacity-25' : ''}`}
                disabled={form.data.processing}
                onClick={confirmPassword}
              >
                {button}
              </PrimaryButton>
            </div>
          </>
        }
      ></DialogModal>
    </span>
  );
};

export default ConfirmPasswordModal;

// _TO_CONVERT_NOW/0example-react-recent/Components/ConfirmsPassword.vue
<script lang="ts" setup>
import { ref, reactive, nextTick } from 'vue';
import DialogModal from './DialogModal.vue';
import InputError from './InputError.vue';
import PrimaryButton from './PrimaryButton.vue';
import SecondaryButton from './SecondaryButton.vue';
import TextInput from './TextInput.vue';

const emit = defineEmits(['confirmed']);

defineProps({
  title: {
    type: String,
    default: 'Confirm Password',
  },
  content: {
    type: String,
    default: 'For your security, please confirm your password to continue.',
  },
  button: {
    type: String,
    default: 'Confirm',
  },
});

const confirmingPassword = ref(false);

const form = reactive({
  password: '',
  error: '',
  processing: false,
});

const passwordInput = ref(null);

const startConfirmingPassword = () => {
  axios.get(route('password.confirmation')).then((response) => {
    if (response.data.confirmed) {
      emit('confirmed');
    } else {
      confirmingPassword.value = true;

      setTimeout(() => passwordInput.value.focus(), 250);
    }
  });
};

const confirmPassword = () => {
  form.processing = true;

  axios
    .post(route('password.confirm'), {
      password: form.password,
    })
    .then(() => {
      form.processing = false;

      closeModal();
      nextTick().then(() => emit('confirmed'));
    })
    .catch((error) => {
      form.processing = false;
      form.error = error.response.data.errors.password[0];
      passwordInput.value.focus();
    });
};

const closeModal = () => {
  confirmingPassword.value = false;
  form.password = '';
  form.error = '';
};
</script>

<template>
  <span>
    <span @click="startConfirmingPassword">
      <slot />
    </span>

    <DialogModal :show="confirmingPassword" @close="closeModal">
      <template #title>
        {{ title }}
      </template>

      <template #content>
        {{ content }}

        <div class="mt-4">
          <TextInput
            ref="passwordInput"
            v-model="form.password"
            type="password"
            class="mt-1 block w-3/4"
            placeholder="Password"
            autocomplete="current-password"
            @keyup.enter="confirmPassword"
          />

          <InputError :message="form.error" class="mt-2" />
        </div>
      </template>

      <template #footer>
        <SecondaryButton @click="closeModal"> Cancel </SecondaryButton>

        <PrimaryButton class="ms-3" :class="{ 'opacity-25': form.processing }" :disabled="form.processing" @click="confirmPassword">
          {{ button }}
        </PrimaryButton>
      </template>
    </DialogModal>
  </span>
</template>
