// _TO_CONVERT_NOW/0example-react/Components/ActionSection.vue
<script lang="ts" setup>
import SectionTitle from './SectionTitle.vue';
</script>

<template>
  <div class="md:grid md:grid-cols-3 md:gap-6">
    <SectionTitle>
      <template #title>
        <slot name="title" />
      </template>
      <template #description>
        <slot name="description" />
      </template>
    </SectionTitle>

    <div class="mt-5 md:mt-0 md:col-span-2">
      <div class="px-4 py-5 sm:p-6 bg-white shadow sm:rounded-lg">
        <slot name="content" />
      </div>
    </div>
  </div>
</template>

// _TO_CONVERT_NOW/0example-react/Components/ActionSection.tsx
import React, { ReactNode } from 'react';
import SectionTitle from './SectionTitle';

interface MyComponentProps {
  title: ReactNode;
  description: ReactNode;
  content: ReactNode;
}

const MyComponent: React.FC<MyComponentProps> = ({ title, description, content }) => {
  return (
    <div className="md:grid md:grid-cols-3 md:gap-6">
      <SectionTitle title={title} description={description} />

      <div className="mt-5 md:mt-0 md:col-span-2">
        <div className="px-4 py-5 bg-white shadow sm:p-6 dark:bg-gray-800 sm:rounded-lg">{content}</div>
      </div>
    </div>
  );
};

export default MyComponent;
