// _TO_CONVERT_NOW/0example-react-recent/Components/DialogModal.tsx
import React from 'react';
import Modal from './Modal';

interface DialogModalProps {
  show: boolean;
  maxWidth?: 'sm' | 'md' | 'lg' | 'xl' | '2xl';
  closeable?: boolean;
  onClose: () => void;
  title: React.ReactNode;
  content: React.ReactNode;
  footer?: React.ReactNode;
}

const DialogModal: React.FC<DialogModalProps> = ({ show = false, maxWidth = '2xl', closeable = true, onClose, title, content, footer }) => {
  return (
    <Modal show={show} maxWidth={maxWidth} closeable={closeable} onClose={onClose}>
      <div className="px-6 py-4">
        <div className="text-lg font-medium text-gray-900 dark:text-gray-100">{title}</div>
        <div className="mt-4 text-sm text-gray-600 dark:text-gray-400">{content}</div>
      </div>
      <div className="flex flex-row justify-end px-6 py-4 bg-gray-100 dark:bg-gray-800 text-end">{footer}</div>
    </Modal>
  );
};

export default DialogModal;

// _TO_CONVERT_NOW/0example-react/Components/DialogModal.vue
<script lang="ts" setup>
import Modal from './Modal.vue';

const emit = defineEmits(['close']);

defineProps({
  show: {
    type: Boolean,
    default: false,
  },
  maxWidth: {
    type: String,
    default: '2xl',
  },
  closeable: {
    type: Boolean,
    default: true,
  },
});

const close = () => {
  emit('close');
};
</script>

<template>
  <Modal :show="show" :max-width="maxWidth" :closeable="closeable" @close="close">
    <div class="px-6 py-4">
      <div class="text-lg font-medium text-gray-900">
        <slot name="title" />
      </div>

      <div class="mt-4 text-sm text-gray-600">
        <slot name="content" />
      </div>
    </div>

    <div class="flex flex-row justify-end px-6 py-4 bg-gray-100 text-end">
      <slot name="footer" />
    </div>
  </Modal>
</template>
